STRATEGY_DESCRIPTIONS = {
    "momentum_topn_v1": {
        "name": "Momentum Top-N (12M)",
        "one_liner": "Top-N assets by trailing returns.",
        "inputs": ["adj_close"],
        "params": {
            "lookback_days": {"type": "int", "default": 252, "desc": "Lookback window"},
            "top_n": {"type": "int", "default": 10, "desc": "Number of assets"},
            "rebalance": {"type": "str", "default": "monthly", "desc": "Rebalance freq"},
        },
        "rebalance": "monthly",
        "risk": "Momentum crashes in sharp reversals.",
        "market_regime": "Trending markets",
    },
    "rsi_mean_reversion_v1": {
        "name": "RSI Mean Reversion",
        "one_liner": "Buy oversold, sell on mean reversion.",
        "inputs": ["adj_close"],
        "params": {
            "symbol": {"type": "str", "default": "SPY", "desc": "Target symbol"},
            "rsi_window": {"type": "int", "default": 14, "desc": "RSI window"},
            "entry_rsi": {"type": "float", "default": 30, "desc": "Entry threshold"},
            "exit_rsi": {"type": "float", "default": 50, "desc": "Exit threshold"},
        },
        "rebalance": "daily",
        "risk": "Can underperform in strong trends.",
        "market_regime": "Range-bound",
    },
    "trend_sma200_v1": {
        "name": "Trend SMA200",
        "one_liner": "Risk-on above SMA, risk-off below.",
        "inputs": ["adj_close"],
        "params": {
            "benchmark_symbol": {"type": "str", "default": "SPY", "desc": "Regime benchmark"},
            "sma_window": {"type": "int", "default": 200, "desc": "SMA window"},
        },
        "rebalance": "daily",
        "risk": "Whipsaw in sideways markets.",
        "market_regime": "Trend-following",
    },
    "low_volatility": {
        "name": "Low Volatility",
        "one_liner": "Select low-volatility assets.",
        "inputs": ["adj_close"],
        "params": {
            "lookback_days": {"type": "int", "default": 60, "desc": "Volatility window"},
            "top_k": {"type": "int", "default": 10, "desc": "Number of assets"},
            "weighting": {
                "type": "str",
                "default": "inverse_vol",
                "desc": "'equal' or 'inverse_vol'",
            },
            "rebalance": {"type": "str", "default": "monthly", "desc": "Rebalance freq"},
        },
        "rebalance": "monthly",
        "risk": "May lag in sharp rallies.",
        "market_regime": "Defensive",
    },
    "vol_adj_momentum": {
        "name": "Volatility-Adjusted Momentum",
        "one_liner": "Rank by return/volatility.",
        "inputs": ["adj_close"],
        "params": {
            "lookback_days": {"type": "int", "default": 252, "desc": "Return window"},
            "vol_window": {"type": "int", "default": 60, "desc": "Volatility window"},
            "top_k": {"type": "int", "default": 10, "desc": "Number of assets"},
            "rebalance": {"type": "str", "default": "monthly", "desc": "Rebalance freq"},
        },
        "rebalance": "monthly",
        "risk": "Still exposed to momentum crashes.",
        "market_regime": "Trending with volatility control",
    },
    "risk_on_off": {
        "name": "Risk-On / Risk-Off Rotation",
        "one_liner": "Switch between risk assets and cash based on regime.",
        "inputs": ["adj_close"],
        "params": {
            "benchmark_symbol": {"type": "str", "default": "SPY", "desc": "Regime benchmark"},
            "sma_window": {"type": "int", "default": 200, "desc": "Regime SMA"},
            "lookback_days": {"type": "int", "default": 126, "desc": "Risk-on momentum window"},
            "top_k": {"type": "int", "default": 10, "desc": "Number of assets"},
            "rebalance": {"type": "str", "default": "monthly", "desc": "Rebalance freq"},
        },
        "rebalance": "monthly",
        "risk": "False signals in choppy regimes.",
        "market_regime": "Regime switching",
    },
}
