UNIVERSE_PRESETS = {
    "US_TOP_10": {
        "preset_id": "US_TOP_10",
        "name": "US Top 10",
        "description": "Top 10 large-cap US equities",
        "tickers": [
            "AAPL",
            "MSFT",
            "NVDA",
            "AMZN",
            "META",
            "GOOGL",
            "BRK.B",
            "LLY",
            "AVGO",
            "TSLA",
        ],
    },
    "US_TECH_8": {
        "preset_id": "US_TECH_8",
        "name": "US Tech 8",
        "description": "Large-cap US tech focus",
        "tickers": [
            "AAPL",
            "MSFT",
            "NVDA",
            "AMZN",
            "META",
            "GOOGL",
            "TSLA",
            "AMD",
        ],
    },
    "US_CORE_20": {
        "preset_id": "US_CORE_20",
        "name": "US Core 20",
        "description": "Diversified US large-caps",
        "tickers": [
            "AAPL",
            "MSFT",
            "NVDA",
            "AMZN",
            "META",
            "GOOGL",
            "BRK.B",
            "LLY",
            "AVGO",
            "TSLA",
            "JPM",
            "V",
            "JNJ",
            "PG",
            "XOM",
            "UNH",
            "COST",
            "HD",
            "MA",
            "MRK",
        ],
    },
}
